name: Playwright Tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout Repository
        id: checkout-repository
        uses: actions/checkout@v3
      - name: Setup Node
        id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: modules-${{ hashFiles('package-lock.json') }}
      - name: Cache Playwright Binaries
        id: cache-playwright
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/ms-playwright
          key: playwright-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        id: install-dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci
      - name: Install Playwright Browsers
        id: install-playwright-browsers
        if: steps.cache-playwright.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps

  e2e-test:
    name: E2E tests - ${{ matrix.project }} - Shard ${{ matrix.shardIndex }} of ${{ matrix.shardTotal }}
    runs-on: ubuntu-latest
    needs: install
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        project: [chromium, firefox, webkit]
        shardIndex: [1, 2]
        shardTotal: [2]
    steps:
      - name: Checkout Repository
        id: checkout-repository
        uses: actions/checkout@v3
      - name: Setup Node
        id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: modules-${{ hashFiles('package-lock.json') }}
      - name: Cache Playwright Binaries
        id: cache-playwright
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/ms-playwright
          key: playwright-${{ hashFiles('package-lock.json') }}
      - name: Install Playwright System Dependencies
        id: install-playwright-system-dependencies
        run: npx playwright install-deps ${{ matrix.project }}
      - name: Run Playwright E2E tests
        id: run-playwright-tests
        run: npx playwright test --project=${{ matrix.project }} --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
        env:
          BASE_URL: ${{vars.BASE_URL}}
          PW_USERNAME: ${{vars.PW_USERNAME}}
          PW_PASSWORD: ${{secrets.PW_PASSWORD}}
          CI: true
      - name: Upload Playwright HTML Reports for E2E tests
        id: upload-playwright-html-report-for-e2e-tests
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report-e2e-tests-${{ matrix.project }}-${{ matrix.shardIndex }}_${{ matrix.shardTotal }}
          path: playwright-report/
          if-no-files-found: ignore
          retention-days: 1

  api-test:
    name: API tests
    runs-on: ubuntu-latest
    needs: install
    timeout-minutes: 30
    steps:
      - name: Checkout Repository
        id: checkout-repository
        uses: actions/checkout@v3
      - name: Setup Node
        id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: modules-${{ hashFiles('package-lock.json') }}
      - name: Cache Playwright Binaries
        id: cache-playwright
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/ms-playwright
          key: playwright-${{ hashFiles('package-lock.json') }}
      - name: Install Playwright System Dependencies
        id: install-playwright-system-dependencies
        run: npx playwright install-deps
      - name: Run Playwright API tests
        id: run-playwright-tests
        run: npx playwright test --project=api-tests
        env:
          BASE_URL: ${{vars.BASE_URL}}
          PW_USERNAME: ${{vars.PW_USERNAME}}
          PW_PASSWORD: ${{secrets.PW_PASSWORD}}
          CI: true
      - name: Upload Playwright HTML Reports for API tests
        id: upload-playwright-html-report-for-api-tests
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report-api-tests
          path: playwright-report/
          if-no-files-found: ignore
          retention-days: 1

  report:
    name: Merge Playwright Reports
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: [e2e-test, api-test]
    timeout-minutes: 30
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout Repository
        id: checkout-repository
        uses: actions/checkout@v3
      - name: Setup Node
        id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: modules-${{ hashFiles('package-lock.json') }}
      - name: Cache Playwright Binaries
        id: cache-playwright
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/ms-playwright
          key: playwright-${{ hashFiles('package-lock.json') }}
      - name: Download Artifacts
        id: download-artifacts
        uses: actions/download-artifact@v3
      - name: Merge Playwright HTML Reports
        id: merge-playwright-html-reports
        run: npm run merge:reports
      - name: Move to merged-report folder
        id: move-to-merged-report-folder
        run: |
          mv merged-html-report merged-report/
        shell: bash
      - name: Upload Merged Playwright HTML Report
        id: upload-merged-playwright-html-report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: mergedReport
          path: merged-report/
          retention-days: 1
