name: Playwright Tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright API tests
        run: npx playwright test api-tests
        env:
          BASE_URL: ${{vars.BASE_URL}}
          PW_USERNAME: ${{vars.PW_USERNAME}}
          PW_PASSWORD: ${{secrets.PW_PASSWORD}}
          CI: true
      - name: Run Playwright UI integration tests
        run: npx playwright test ui-integration-tests
        env:
          BASE_URL: ${{vars.BASE_URL}}
          PW_USERNAME: ${{vars.PW_USERNAME}}
          PW_PASSWORD: ${{secrets.PW_PASSWORD}}
          CI: true
      - name: Run Playwright UI E2E tests
        run: npx playwright test ui-e2e-tests
        env:
          BASE_URL: ${{vars.BASE_URL}}
          PW_USERNAME: ${{vars.PW_USERNAME}}
          PW_PASSWORD: ${{secrets.PW_PASSWORD}}
          CI: true
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
